name: Broadcast schedule

# التشغيل آلياً كل 10 دقائق + خيار تشغيل يدوي
on:
  schedule:
    - cron: '*/10 * * * *'   # كل 10 دقائق
  workflow_dispatch:

jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run broadcast once
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          BROADCAST_CHAT_ID: ${{ secrets.BROADCAST_CHAT_ID }} # optional
        run: |
          python broadcast_once.py
